import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'

const WS_URL = 'ws://localhost:5001'

export default function Home() {
  const [socket, setSocket] = useState<WebSocket>(null)

  // useEffectはレンダリング後に実行
  useEffect(() => {
    // サーバ側ではWebSocketが使えないのでスキップ
    if (!process.browser) return

    // WebSocket初期化
    setSocket(new WebSocket(WS_URL))

    // 接続時
    socket.addEventListener('open', (e) => {
      console.log('open')
    })

    // メッセージが来たとき
    socket.addEventListener('message', (e) => {
      console.log(`message: ${new Date().toISOString()}\n${e.data}`)
    })

    // 切断時
    socket.addEventListener('close', (e) => {
      console.log('close')
      console.log(e)
    })

    // 接続エラー (サーバ側起動してない等)
    socket.addEventListener('error', (e) => {
      console.log('error')
      console.log(e)
    })
    return () => {
      socket.close()
    }
  }, [socket])
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a href="https://github.com/vercel/next.js/tree/master/examples" className={styles.card}>
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>Instantly deploy your Next.js site to a public URL with Vercel.</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
